"""How often does the app hand a child a confident WRONG answer — today, and with a repair?

`assign_sim.py` measured the wrong headline for the safety question. It counted stickers and
"cubes read perfectly", but the number that decides whether a repair is safe to ship is neither:
it is **how often a wrong reading passes the legality gate**, because that is the only kind of
error the app cannot refuse. An illegal reading is caught and the user is asked to show a side
again — visible, attributable, recoverable. A legal-but-wrong reading is walked confidently
through twenty moves for a cube nobody is holding.

So this simulates whole LEGAL cubes, not multisets:

  * cubes are generated by the app's own cubejs (`Cube.random()`), so every truth is reachable;
  * the six faces are the real facelet blocks, and each face draws its sticker scores from ONE
    held-out photo, because nine stickers in one frame share one exposure and one patch of light;
  * legality is decided by `isCubeState` — the app's own reachability round-trip, the same gate
    the cube registry and the reconnect readings are parsed with, so this cannot drift from what
    the app actually accepts. A parity check re-written here could.

Reported for both the shipped argmax and the nine-of-each assignment:

    correct        the reading is the cube
    refused        the reading is not a legal cube — the app says so and asks for a side again
    QUIET FAILURE  the reading is legal, and wrong

    ml/venv/bin/python ml/quiet_failure.py --trials 20000
"""

from __future__ import annotations

import argparse
import json
import subprocess

import numpy as np

from assign_sim import NAMES, NC, PER_COLOUR, assign, collect

# cubejs facelet strings are URFDLB; the detector's classes are white, red, green, yellow, orange,
# blue. The Western colour scheme puts those in exactly that order, which is why this is a plain
# positional map and not a lookup table anyone has to maintain.
FACE_LETTERS = "URFDLB"
LETTER_TO_CLASS = {ch: i for i, ch in enumerate(FACE_LETTERS)}


def oracle(cmd: list[str], payload: object | None = None) -> object:
    out = subprocess.run(
        ["node", "cube_oracle.mjs", *cmd],
        input=None if payload is None else json.dumps(payload),
        capture_output=True, text=True, cwd=".", check=True,
    )
    return json.loads(out.stdout)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", default="../apps/web/vendor/cube-yolo.onnx")
    ap.add_argument("--trials", type=int, default=20000)
    ap.add_argument("--seed", type=int, default=20260830)
    args = ap.parse_args()

    pool, per_photo = collect(args.model)
    rng = np.random.default_rng(args.seed)

    print(f"\ngenerating {args.trials} legal cubes from the app's own cubejs…")
    truths: list[str] = oracle(["gen", str(args.trials)])  # type: ignore[assignment]

    argmax_reads: list[str] = []
    assign_reads: list[str] = []
    fallbacks = 0
    for t in truths:
        true_cls = np.array([LETTER_TO_CLASS[ch] for ch in t])
        draw = np.empty((54, NC), dtype=np.float64)
        for f in range(6):  # a face is one photograph: nine stickers, one exposure
            photo = per_photo[rng.integers(len(per_photo))]
            for i in range(f * 9, (f + 1) * 9):
                c = int(true_cls[i])
                src = photo[c] if photo[c] else pool[c]
                if not photo[c]:
                    fallbacks += 1
                draw[i] = src[rng.integers(len(src))]
        p = np.clip(draw, 1e-9, None)
        logp = np.log(p / p.sum(axis=1, keepdims=True))
        argmax_reads.append("".join(FACE_LETTERS[c] for c in logp.argmax(axis=1)))
        assign_reads.append("".join(FACE_LETTERS[c] for c in assign(logp)))

    print("checking every reading through the app's own legality gate…")
    # A gate that rejected everything would report zero quiet failures too, and look like success.
    # The truths are legal by construction, so every one of them must pass; if they do not, the
    # bridge is broken and every number below is meaningless.
    if not all(oracle(["check"], truths)):  # type: ignore[arg-type]
        raise SystemExit("the legality gate rejected a cube cubejs itself generated — bridge is broken")
    legal_argmax: list[bool] = oracle(["check"], argmax_reads)  # type: ignore[assignment]
    legal_assign: list[bool] = oracle(["check"], assign_reads)  # type: ignore[assignment]

    def tally(reads: list[str], legal: list[bool]) -> dict[str, int]:
        t = {"correct": 0, "refused": 0, "quiet": 0}
        for truth, read, ok in zip(truths, reads, legal):
            if read == truth:
                t["correct"] += 1
            elif ok:
                t["quiet"] += 1  # legal, and not the cube in the hand
            else:
                t["refused"] += 1
        return t

    n = args.trials
    a, b = tally(argmax_reads, legal_argmax), tally(assign_reads, legal_assign)
    print(f"    (fell back to the global pool for {fallbacks} of {n * 54} stickers — {100 * fallbacks / (n * 54):.1f}%)")
    print(f"\n--- {n} legal cubes, each face drawn from one held-out photo ---\n")
    print(f"{'':<16}{'argmax (shipped)':>20}{'9-of-each assign':>20}")
    for k, label in (("correct", "read correctly"), ("refused", "refused — re-scan"), ("quiet", "QUIET FAILURE")):
        print(f"  {label:<14}{a[k]:>9} ({100*a[k]/n:5.2f}%){b[k]:>9} ({100*b[k]/n:5.2f}%)")
    print()
    print(f"  a wrong reading is refused rather than accepted:")
    for name, t in (("argmax", a), ("assign", b)):
        wrong = t["refused"] + t["quiet"]
        share = f"{100 * t['refused'] / wrong:.1f}%" if wrong else "—"
        print(f"    {name:<8} {t['refused']}/{wrong} wrong readings caught = {share}")


if __name__ == "__main__":
    main()
