// Capture the cube's CURRENT state from the live device and regenerate the
// web spike's state.js (dev-docs/spikes/cube-state/state.js).
//
// Usage: npm run spike:refresh   (keep the cube gently moving so it stays awake)
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import Cube from 'cubejs';
import { GanCube } from '../src/driver.js';
import { extractMacFromManufacturerData } from '../src/mac.js';
import { BlewTransport, scanForCube } from '../src/transport/blew.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SCAN_ADV = join(ROOT, 'scripts', 'scan-adv');
const STATE_JS = join(ROOT, '..', 'dev-docs', 'spikes', 'cube-state', 'state.js');

function setupAlgFor(facelets: string): string {
  Cube.initSolver();
  const solution = Cube.fromString(facelets).solve(); // state -> solved
  const invert = (m: string) => (m.endsWith('2') ? m : m.endsWith("'") ? m[0]! : `${m}'`);
  const alg = solution.trim().split(/\s+/).reverse().map(invert).join(' ');
  const check = new Cube();
  check.move(alg);
  if (check.asString() !== facelets) throw new Error('setup-alg self-check failed');
  return alg;
}

async function main() {
  process.stdout.write('scanning — give the cube a twist to wake it…\n');
  let dev: Awaited<ReturnType<typeof scanForCube>>[number] | undefined;
  for (let i = 0; i < 6 && !dev; i++) {
    const devices = await scanForCube(SCAN_ADV, 10);
    dev = devices.find((d) => /gan/i.test(d.name) && d.manufacturerData);
  }
  if (!dev?.manufacturerData) throw new Error('cube never advertised — keep it moving and retry');
  const mac = extractMacFromManufacturerData(dev.manufacturerData);
  if (!mac) throw new Error('could not recover MAC from advertisement');

  const cube = new GanCube({ mac, transport: new BlewTransport(dev.id) });
  cube.on('error', (e: Error) => console.error('error:', e.message));
  cube.connect();
  process.stdout.write('connected — reading state (keep it gently moving, no face turns)…\n');
  const st = await cube.getState({ timeoutMs: 25000 });
  cube.disconnect();

  const stamp = new Date().toISOString().replace(/\.\d+Z$/, 'Z');
  const setupAlg = setupAlgFor(st.facelets);
  const js = `// Regenerated by spike:refresh from the live cube.
window.CUBE_STATE = {
  device: ${JSON.stringify(dev.name)},
  capturedAt: ${JSON.stringify(stamp)},
  facelets: ${JSON.stringify(st.facelets)},
  setupAlg: ${JSON.stringify(setupAlg)},
  source: 'live',
};
`;
  writeFileSync(STATE_JS, js);
  console.log(`\nwrote ${STATE_JS}`);
  console.log(`facelets: ${st.facelets}`);
  console.log('open dev-docs/spikes/cube-state/index.html to view.');
}
main().catch((e: unknown) => {
  console.error('spike:refresh failed:', e instanceof Error ? e.message : String(e));
  process.exitCode = 1;
});
