fn main() {
    // tauri-build does not add icons/** to Cargo's input set, so without these
    // the binary keeps embedding the previous icons after they are
    // regenerated: the new files are on disk, the old icon is still in the
    // Dock. The failure is silent and survives a `cargo build` that reports
    // success, which is what makes it cost an afternoon.
    println!("cargo:rerun-if-changed=icons");
    println!("cargo:rerun-if-changed=icons/icon.icns");
    println!("cargo:rerun-if-changed=icons/icon.png");
    println!("cargo:rerun-if-changed=icons/icon.ico");
    println!("cargo:rerun-if-changed=icons/icon.svg");
    println!("cargo:rerun-if-changed=icons/icon-square.svg");
    // The macOS 26 layered icon: the compiled catalogue that ships in the
    // bundle, and the source it is built from. Assets.car is generated by
    // scripts/build-macos-glass-icon.sh and committed, so a stale one here is
    // the same failure mode as a stale .icns.
    println!("cargo:rerun-if-changed=icons/Assets.car");
    println!("cargo:rerun-if-changed=icons/Cubus.icon");
    println!("cargo:rerun-if-changed=Info.plist");
    println!("cargo:rerun-if-changed=tauri.conf.json");

    tauri_build::build()
}
