// Every shipped challenge, verified against the independent oracle: the scramble really
// reaches the state, the solution really solves it, and every length agrees. Minimality
// itself was proved offline by crates/optimal-solver (whose §7 verification bar is its own
// test suite); what this file guarantees is that no entry can drift from being a real,
// self-consistent position — hand-edited numbers have nowhere to hide.

import assert from 'node:assert/strict';
import { test } from 'node:test';
import { existsSync } from 'node:fs';

const data = new URL('../lib/data/optimal-challenges.json', import.meta.url);
const vendored = new URL('../vendor/cubejs.js', import.meta.url);

test('every challenge is a real position with self-consistent proof numbers', async (t) => {
  if (!existsSync(data)) {
    // The artifact is generated by `cargo run --release -p optimal-solver --bin gen-library`
    // and committed; a checkout between generation and commit may not have it yet.
    t.skip('lib/data/optimal-challenges.json not generated yet');
    return;
  }
  assert.ok(existsSync(vendored), 'vendor/cubejs.js is missing — run `pnpm vendor:libs`');
  const Cube = (await import(vendored)).default;
  const { validateChallenges } = await import('../lib/optimal-challenges.js');
  const { readFileSync } = await import('node:fs');
  // The oracle rides inside the validator now — the same checks production makes.
  const challenges = validateChallenges(JSON.parse(readFileSync(data, 'utf8')), { Cube });
  assert.ok(challenges.length >= 1);
  for (const [i, c] of challenges.entries()) {
    // The scramble applied to solved reaches exactly the state…
    const scrambled = new Cube();
    if (c.scramble.trim()) scrambled.move(c.scramble);
    assert.equal(scrambled.asString(), c.facelets, `entry ${i}: scramble does not reach the state`);
    // …and the proved-minimal solution solves it.
    const oracle = Cube.fromString(c.facelets);
    if (c.optimalSolution.trim()) oracle.move(c.optimalSolution);
    assert.ok(oracle.isSolved(), `entry ${i}: the "minimal" solution does not solve the cube`);
    // The scramble is the inverse of the solution, so its length is the optimal length too.
    assert.equal(c.scramble.trim().split(/\s+/).filter(Boolean).length, c.optimalLength,
      `entry ${i}: scramble length disagrees with the proved length`);
  }
});

test('the validator refuses to run without the oracle — structural-only is not a mode', async () => {
  const { validateChallenges } = await import('../lib/optimal-challenges.js');
  assert.throws(() => validateChallenges([{}], {}), /requires the cubejs oracle/);
  assert.throws(() => validateChallenges([{}]), /requires the cubejs oracle/);
});

// ---- the lookup the app actually uses ---------------------------------------------------------
//
// The library existed, was validated, and was wired to nothing: before this, `grep -rl
// optimal-challenges apps/web` returned only the module and this file. What follows covers the
// path that makes it worth shipping — a known state answered from data, with no search and no
// native proof — and the one property that path must never lose: a minimality claim can only
// come from entries that passed the validator.

test('a known state answers from the library, and an unknown one does not', async () => {
  const { indexChallenges, provenAnswer } = await import('../lib/optimal-challenges.js');
  const entry = { facelets: 'U'.repeat(54), scramble: '', optimalLength: 3, optimalSolution: "R U R'" };
  const index = indexChallenges([entry]);

  assert.deepEqual(provenAnswer(index, entry.facelets),
    { moves: 3, alg: "R U R'", setupAlg: '' }, 'the setup alg rides along, so neither search runs');
  assert.equal(provenAnswer(index, 'D'.repeat(54)), null, 'an unlisted state is a miss, not a guess');
});

test('an empty library misses on everything rather than failing', async () => {
  // A library that did not load costs performance, never correctness: every lookup misses and
  // the app searches exactly as it always did. So the miss path must be total and quiet.
  const { NO_CHALLENGES, provenAnswer } = await import('../lib/optimal-challenges.js');
  assert.equal(provenAnswer(NO_CHALLENGES, 'U'.repeat(54)), null);
  assert.equal(provenAnswer(null, 'U'.repeat(54)), null, 'no index at all is also just a miss');
  assert.equal(provenAnswer(undefined, 'U'.repeat(54)), null);
  // Object.freeze(new Map()) would NOT have given this: freezing a Map leaves set() working,
  // so an "empty, frozen" index could quietly gain an entry nobody validated.
  assert.throws(() => NO_CHALLENGES.set('x', 1), TypeError, 'nothing can populate it by accident');
  assert.throws(() => { NO_CHALLENGES.get = () => ({ optimalLength: 1 }); }, TypeError,
    'and nothing can replace its lookup with one that answers');
});

test('the whole load path runs, and a library that will not validate yields no index at all', async () => {
  // loadChallenges is the function the app calls and the one nothing exercised, because node's
  // fetch cannot read a file: URL. With the fetch injected it is drivable end to end — and the
  // case that matters is the failure: a bad library must throw, so app.js drops the whole index
  // rather than serving a claim from entries nobody checked.
  const Cube = (await import(vendored)).default;
  const { loadChallenges } = await import('../lib/optimal-challenges.js');
  const { readFileSync } = await import('node:fs');
  const real = JSON.parse(readFileSync(data, 'utf8'));

  const serve = (body, ok = true) => async () => ({ ok, status: ok ? 200 : 404, json: async () => body });

  const loaded = await loadChallenges({ Cube, fetch: serve(real) });
  assert.equal(loaded.length, real.length, 'the shipped library loads through the real path');

  // One digit changed. Structurally perfect, and a lie.
  const tampered = JSON.parse(JSON.stringify(real));
  tampered[0].optimalLength += 1;
  await assert.rejects(() => loadChallenges({ Cube, fetch: serve(tampered) }), /its algs disagree/);

  // And an alg that is not in the metric at all: refused by the GRAMMAR, before any oracle work.
  // This fixture used to stand for "a solution that does not solve", and it never reached that
  // check — entry 0's solution begins with `L'`, so priming it again spells `L''` and htmMoves
  // rejects it (found by the 2026-09-05 audit; the oracle paths it was standing in for are the
  // test below). Kept, because the grammar gate is worth pinning on its own — with the message
  // that says WHICH refusal fired.
  const wrong = JSON.parse(JSON.stringify(real));
  wrong[0].optimalSolution = wrong[0].optimalSolution.replace(/^(\S+)/, "$1'");
  await assert.rejects(() => loadChallenges({ Cube, fetch: serve(wrong) }), /is not a face turn/);

  await assert.rejects(() => loadChallenges({ Cube, fetch: serve(real, false) }), /did not load \(404\)/);
});

test('a library that contradicts itself is refused, not silently deduplicated', async () => {
  // `new Map(pairs)` resolves a duplicate key by last-write-wins, so two entries for one state
  // — each internally consistent, disagreeing on the minimum — would have produced a claim
  // chosen by array order. There is no right answer to pick between them; there is only
  // refusing the library.
  const { indexChallenges } = await import('../lib/optimal-challenges.js');
  const state = 'U'.repeat(54);
  const a = { facelets: state, scramble: '', optimalLength: 3, optimalSolution: "R U R'" };
  const b = { facelets: state, scramble: '', optimalLength: 4, optimalSolution: "R U R' U" };
  assert.throws(() => indexChallenges([a, b]), /two entries claim the same state/);
  assert.doesNotThrow(() => indexChallenges([a]), 'a library without duplicates still indexes');
});

test('every way the library can fail leaves through the same door', async () => {
  // The bug this closes was in the CALL SITE, not the validator: `.then(f, r)` does not route
  // a throw from `f` to `r`, so a duplicate-key refusal — thrown by indexChallenges inside the
  // fulfillment handler — became an unhandled rejection while the app searched on, silently.
  // loadIndex exists so no call site has to get that idiom right.
  const Cube = (await import(vendored)).default;
  const { loadIndex, NO_CHALLENGES } = await import('../lib/optimal-challenges.js');
  const { readFileSync } = await import('node:fs');
  const real = JSON.parse(readFileSync(data, 'utf8'));
  const serve = (body, ok = true) => async () => ({ ok, status: ok ? 200 : 404, json: async () => body });

  const good = await loadIndex({ Cube, fetch: serve(real) });
  assert.equal(good.size, real.length, 'a good library still indexes');

  // Failure one: it does not load.
  let seen = null;
  const gone = await loadIndex({ Cube, fetch: serve(real, false), onError: (e) => { seen = e; } });
  assert.equal(gone, NO_CHALLENGES, 'a library that will not load yields no index');
  assert.match(String(seen), /did not load \(404\)/, 'and says why');

  // Failure two: it loads and contradicts itself. This is the one that used to escape.
  seen = null;
  const dupes = [real[0], { ...real[0] }];
  const bad = await loadIndex({ Cube, fetch: serve(dupes), onError: (e) => { seen = e; } });
  assert.equal(bad, NO_CHALLENGES, 'a self-contradicting library yields no index either');
  assert.match(String(seen), /two entries claim the same state/, 'and reaches the caller rather than the void');
});

test('the two ORACLE refusals fire, on fixtures the grammar gate cannot catch', async () => {
  // The gap the 2026-09-05 audit found: every "bad library" fixture in this file was rejected by
  // the tokenizer or by an arithmetic length check, so the two checks that actually need cubejs —
  // does the scramble reach the state, does the "minimal" solution solve it — had never once been
  // observed to fire. Deleting either would have left this file green.
  //
  // Each fixture is therefore proved to BE what it claims first: same length, strict HTM, and
  // genuinely wrong. A fixture that trips an earlier gate tests that gate, not this one.
  const Cube = (await import(vendored)).default;
  const { validateChallenges, loadIndex, NO_CHALLENGES } = await import('../lib/optimal-challenges.js');
  const { htmMoves } = await import('../lib/optimal.js');
  const { readFileSync } = await import('node:fs');
  const real = JSON.parse(readFileSync(data, 'utf8'));
  const serve = (body) => async () => ({ ok: true, status: 200, json: async () => body });

  /** One move swapped for a different face, keeping the modifier — so the alg stays strict HTM
   *  and exactly as long, and only its EFFECT changes. */
  const swapLastFace = (alg) => {
    const tokens = alg.trim().split(/\s+/);
    const last = tokens[tokens.length - 1];
    tokens[tokens.length - 1] = (last[0] === 'L' ? 'R' : 'L') + last.slice(1);
    return tokens.join(' ');
  };

  // 1. A solution that is a real 17-move HTM alg and does not solve the cube.
  const wrong = JSON.parse(JSON.stringify(real));
  wrong[0].optimalSolution = swapLastFace(wrong[0].optimalSolution);
  assert.equal(htmMoves(wrong[0].optimalSolution, 'fixture').length, wrong[0].optimalLength,
    'the fixture must be strict HTM and the claimed length, or an earlier gate catches it');
  const notSolved = Cube.fromString(wrong[0].facelets);
  notSolved.move(wrong[0].optimalSolution);
  assert.equal(notSolved.isSolved(), false, 'the fixture must really fail to solve');
  assert.throws(() => validateChallenges(wrong, { Cube }),
    /entry 0's "minimal" solution does not solve the cube/);

  // 2. A scramble that is a real HTM alg of the claimed length and reaches a DIFFERENT state.
  const drifted = JSON.parse(JSON.stringify(real));
  drifted[0].scramble = swapLastFace(drifted[0].scramble);
  assert.equal(htmMoves(drifted[0].scramble, 'fixture').length, drifted[0].optimalLength);
  const elsewhere = new Cube();
  elsewhere.move(drifted[0].scramble);
  assert.notEqual(elsewhere.asString(), drifted[0].facelets, 'the fixture must really drift');
  assert.throws(() => validateChallenges(drifted, { Cube }),
    /entry 0's scramble does not reach its state/);

  // 3. And both leave the app with the EMPTY index rather than a partial one: a library holding a
  //    single unverifiable entry must cost every lookup, not just that entry's.
  for (const [what, body] of [['a non-solving solution', wrong], ['a drifting scramble', drifted]]) {
    let seen = null;
    const index = await loadIndex({ Cube, fetch: serve(body), onError: (e) => { seen = e; } });
    assert.equal(index, NO_CHALLENGES, `${what} must yield no index at all`);
    assert.match(String(seen), /entry 0/, `${what} must reach the caller, naming the entry`);
  }
});
