// Every shipped challenge, verified against the independent oracle: the scramble really
// reaches the state, the solution really solves it, and every length agrees. Minimality
// itself was proved offline by crates/optimal-solver (whose §7 verification bar is its own
// test suite); what this file guarantees is that no entry can drift from being a real,
// self-consistent position — hand-edited numbers have nowhere to hide.

import assert from 'node:assert/strict';
import { test } from 'node:test';
import { existsSync } from 'node:fs';

const data = new URL('../lib/data/optimal-challenges.json', import.meta.url);
const vendored = new URL('../vendor/cubejs.js', import.meta.url);

test('every challenge is a real position with self-consistent proof numbers', async (t) => {
  if (!existsSync(data)) {
    // The artifact is generated by `cargo run --release -p optimal-solver --bin gen-library`
    // and committed; a checkout between generation and commit may not have it yet.
    t.skip('lib/data/optimal-challenges.json not generated yet');
    return;
  }
  assert.ok(existsSync(vendored), 'vendor/cubejs.js is missing — run `pnpm vendor:libs`');
  const Cube = (await import(vendored)).default;
  const { validateChallenges } = await import('../lib/optimal-challenges.js');
  const { readFileSync } = await import('node:fs');
  // The oracle rides inside the validator now — the same checks production makes.
  const challenges = validateChallenges(JSON.parse(readFileSync(data, 'utf8')), { Cube });
  assert.ok(challenges.length >= 1);
  for (const [i, c] of challenges.entries()) {
    // The scramble applied to solved reaches exactly the state…
    const scrambled = new Cube();
    if (c.scramble.trim()) scrambled.move(c.scramble);
    assert.equal(scrambled.asString(), c.facelets, `entry ${i}: scramble does not reach the state`);
    // …and the proved-minimal solution solves it.
    const oracle = Cube.fromString(c.facelets);
    if (c.optimalSolution.trim()) oracle.move(c.optimalSolution);
    assert.ok(oracle.isSolved(), `entry ${i}: the "minimal" solution does not solve the cube`);
    // The scramble is the inverse of the solution, so its length is the optimal length too.
    assert.equal(c.scramble.trim().split(/\s+/).filter(Boolean).length, c.optimalLength,
      `entry ${i}: scramble length disagrees with the proved length`);
  }
});

test('the validator refuses to run without the oracle — structural-only is not a mode', async () => {
  const { validateChallenges } = await import('../lib/optimal-challenges.js');
  assert.throws(() => validateChallenges([{}], {}), /requires the cubejs oracle/);
  assert.throws(() => validateChallenges([{}]), /requires the cubejs oracle/);
});

// ---- the lookup the app actually uses ---------------------------------------------------------
//
// The library existed, was validated, and was wired to nothing: before this, `grep -rl
// optimal-challenges apps/web` returned only the module and this file. What follows covers the
// path that makes it worth shipping — a known state answered from data, with no search and no
// native proof — and the one property that path must never lose: a minimality claim can only
// come from entries that passed the validator.

test('a known state answers from the library, and an unknown one does not', async () => {
  const { indexChallenges, provenAnswer } = await import('../lib/optimal-challenges.js');
  const entry = { facelets: 'U'.repeat(54), scramble: '', optimalLength: 3, optimalSolution: "R U R'" };
  const index = indexChallenges([entry]);

  assert.deepEqual(provenAnswer(index, entry.facelets),
    { moves: 3, alg: "R U R'", setupAlg: '' }, 'the setup alg rides along, so neither search runs');
  assert.equal(provenAnswer(index, 'D'.repeat(54)), null, 'an unlisted state is a miss, not a guess');
});

test('an empty library misses on everything rather than failing', async () => {
  // A library that did not load costs performance, never correctness: every lookup misses and
  // the app searches exactly as it always did. So the miss path must be total and quiet.
  const { NO_CHALLENGES, provenAnswer } = await import('../lib/optimal-challenges.js');
  assert.equal(provenAnswer(NO_CHALLENGES, 'U'.repeat(54)), null);
  assert.equal(provenAnswer(null, 'U'.repeat(54)), null, 'no index at all is also just a miss');
  assert.equal(provenAnswer(undefined, 'U'.repeat(54)), null);
  // Object.freeze(new Map()) would NOT have given this: freezing a Map leaves set() working,
  // so an "empty, frozen" index could quietly gain an entry nobody validated.
  assert.throws(() => NO_CHALLENGES.set('x', 1), TypeError, 'nothing can populate it by accident');
  assert.throws(() => { NO_CHALLENGES.get = () => ({ optimalLength: 1 }); }, TypeError,
    'and nothing can replace its lookup with one that answers');
});

test('the whole load path runs, and a library that will not validate yields no index at all', async () => {
  // loadChallenges is the function the app calls and the one nothing exercised, because node's
  // fetch cannot read a file: URL. With the fetch injected it is drivable end to end — and the
  // case that matters is the failure: a bad library must throw, so app.js drops the whole index
  // rather than serving a claim from entries nobody checked.
  const Cube = (await import(vendored)).default;
  const { loadChallenges } = await import('../lib/optimal-challenges.js');
  const { readFileSync } = await import('node:fs');
  const real = JSON.parse(readFileSync(data, 'utf8'));

  const serve = (body, ok = true) => async () => ({ ok, status: ok ? 200 : 404, json: async () => body });

  const loaded = await loadChallenges({ Cube, fetch: serve(real) });
  assert.equal(loaded.length, real.length, 'the shipped library loads through the real path');

  // One digit changed. Structurally perfect, and a lie.
  const tampered = JSON.parse(JSON.stringify(real));
  tampered[0].optimalLength += 1;
  await assert.rejects(() => loadChallenges({ Cube, fetch: serve(tampered) }), /its algs disagree/);

  // And a state whose "minimal" solution does not solve it at all.
  const wrong = JSON.parse(JSON.stringify(real));
  wrong[0].optimalSolution = wrong[0].optimalSolution.replace(/^(\S+)/, "$1'");
  await assert.rejects(() => loadChallenges({ Cube, fetch: serve(wrong) }), /optimal-challenges/);

  await assert.rejects(() => loadChallenges({ Cube, fetch: serve(real, false) }), /did not load \(404\)/);
});
