// Every shipped challenge, verified against the independent oracle: the scramble really
// reaches the state, the solution really solves it, and every length agrees. Minimality
// itself was proved offline by crates/optimal-solver (whose §7 verification bar is its own
// test suite); what this file guarantees is that no entry can drift from being a real,
// self-consistent position — hand-edited numbers have nowhere to hide.

import assert from 'node:assert/strict';
import { test } from 'node:test';
import { existsSync } from 'node:fs';

const data = new URL('../lib/data/optimal-challenges.json', import.meta.url);
const vendored = new URL('../vendor/cubejs.js', import.meta.url);

test('every challenge is a real position with self-consistent proof numbers', async (t) => {
  if (!existsSync(data)) {
    // The artifact is generated by `cargo run --release -p optimal-solver --bin gen-library`
    // and committed; a checkout between generation and commit may not have it yet.
    t.skip('lib/data/optimal-challenges.json not generated yet');
    return;
  }
  assert.ok(existsSync(vendored), 'vendor/cubejs.js is missing — run `pnpm vendor:libs`');
  const Cube = (await import(vendored)).default;
  const { validateChallenges } = await import('../lib/optimal-challenges.js');
  const { readFileSync } = await import('node:fs');
  // The oracle rides inside the validator now — the same checks production makes.
  const challenges = validateChallenges(JSON.parse(readFileSync(data, 'utf8')), { Cube });
  assert.ok(challenges.length >= 1);
  for (const [i, c] of challenges.entries()) {
    // The scramble applied to solved reaches exactly the state…
    const scrambled = new Cube();
    if (c.scramble.trim()) scrambled.move(c.scramble);
    assert.equal(scrambled.asString(), c.facelets, `entry ${i}: scramble does not reach the state`);
    // …and the proved-minimal solution solves it.
    const oracle = Cube.fromString(c.facelets);
    if (c.optimalSolution.trim()) oracle.move(c.optimalSolution);
    assert.ok(oracle.isSolved(), `entry ${i}: the "minimal" solution does not solve the cube`);
    // The scramble is the inverse of the solution, so its length is the optimal length too.
    assert.equal(c.scramble.trim().split(/\s+/).filter(Boolean).length, c.optimalLength,
      `entry ${i}: scramble length disagrees with the proved length`);
  }
});

test('the validator refuses to run without the oracle — structural-only is not a mode', async () => {
  const { validateChallenges } = await import('../lib/optimal-challenges.js');
  assert.throws(() => validateChallenges([{}], {}), /requires the cubejs oracle/);
  assert.throws(() => validateChallenges([{}]), /requires the cubejs oracle/);
});
