// The pattern ledger, held to its own claims.
//
// `test/fixtures/pattern-ledger.mjs` is generated by an exhaustive search, so every row is a claim
// about a picture: this maneuver reaches it, it is this many moves, it is fixed by this many of the 24
// views, this many stickers read wrong. None of that is worth having unless it is checked, because a
// generated file that drifted from its generator looks exactly like one that did not.
//
// The expensive half of the claim — that a row's `moves` is MINIMAL — cannot be rechecked here; it
// rests on the search having been exhaustive for its radius, which is the generator's business and
// takes five minutes. What is checked here is everything else, and one anchor on minimality: the three
// named patterns whose minima were independently proved by meet-in-the-middle in
// `bench/solve-to-state-oracle.mjs` must appear at exactly those lengths.

import assert from 'node:assert/strict';
import { test } from 'node:test';

import { MOVE_NAMES, SOLVED, applyAlg, applyMove, movesOf } from '../lib/cube-pieces.js';
import { toFacelets } from '../lib/two-phase.js';
import { FACE_ORDER, canonicalDesign, canonicalLook, symmetryOrder, verify } from '../bench/cube-look.mjs';
import { LEDGER_DEPTH, SET_PATTERNS, STATE_PATTERNS } from './fixtures/pattern-ledger.mjs';
import { SOLVER_PHASES } from '../bench/solver-phases.mjs';
import { PREDICATE } from '../bench/solve-to-state-oracle.mjs';
import { solveByMethod } from '../lib/method-solver.js';
import { lcg, seededScrambles } from './fixtures/seeded-scrambles.mjs';

test('the geometry the ledger rests on checks out against the cube model', () => {
  // 54 distinct sticker places, 24 rotations and 48 symmetries closing under composition, a solved
  // cube symmetric under all of them, and every one of the 18 moves PREDICTED from the geometry and
  // matching what cube-pieces.js and two-phase.js produce. If this fails, nothing below means anything.
  const got = verify();
  assert.deepEqual(got, { stickers: 54, rotations: 24, symmetries: 48, movesChecked: 18 });
});

/** The cube that undoes this one — needed to check the ledger's family key. */
function inverseState(st) {
  const cp = new Array(8), co = new Array(8), ep = new Array(12), eo = new Array(12);
  for (let i = 0; i < 8; i++) { cp[st.cp[i]] = i; co[st.cp[i]] = (3 - st.co[i]) % 3; }
  for (let i = 0; i < 12; i++) { ep[st.ep[i]] = i; eo[st.ep[i]] = st.eo[i]; }
  return { cp, co, ep, eo };
}
const familyKey = (alg) => {
  const cube = applyAlg(SOLVED, alg);
  return [canonicalDesign(toFacelets(cube)), canonicalDesign(toFacelets(inverseState(cube)))].sort()[0];
};

test('each row is a FAMILY: its variants are the same pattern, and no two rows are', () => {
  // The correction the owner caught. Deduplicating only by the 24 rotations counted mirrors and
  // inverses twice: 213 rows where there are 95 patterns. A row now carries its variants, and this is
  // what stops the merge being a claim in a comment.
  const keys = new Set();
  let rotationClasses = 0;
  for (const row of STATE_PATTERNS) {
    const key = familyKey(row.alg);
    assert.ok(!keys.has(key), `${row.alg}: two rows are the same pattern up to mirror and inverse`);
    keys.add(key);
    rotationClasses += 1 + row.variants.length;
    for (const v of row.variants) {
      assert.equal(familyKey(v), key, `${row.alg}: variant ${v} is a different pattern`);
      assert.ok(movesOf(v).length >= row.moves,
        `${row.alg}: variant ${v} is shorter than the representative, which should have been the head`);
      assert.equal(symmetryOrder(toFacelets(applyAlg(SOLVED, v))), row.order,
        `${row.alg}: variant ${v} has a different symmetry order, so it is not in this family`);
    }
    assert.ok(row.designs >= 1 && row.designs <= 2,
      `${row.alg}: a family spans one or two mirror classes, not ${row.designs}`);
  }
  assert.ok(rotationClasses > STATE_PATTERNS.length,
    'no row has any variant — either the dedup did nothing or the field was dropped');
});

test('every ledger row reaches the picture it claims, in the number of moves it claims', () => {
  assert.ok(STATE_PATTERNS.length > 0, 'an empty ledger passes every other assertion here');
  for (const row of STATE_PATTERNS) {
    const facelets = toFacelets(applyAlg(SOLVED, row.alg));
    assert.equal(canonicalLook(facelets), row.look,
      `${row.alg}: the maneuver does not reach the picture this row records`);
    assert.equal(movesOf(row.alg).length, row.moves,
      `${row.alg}: recorded as ${row.moves} moves`);
    assert.ok(row.moves <= LEDGER_DEPTH,
      `${row.alg}: ${row.moves} moves is beyond the search's own radius of ${LEDGER_DEPTH}`);
  }
});

test('every recorded measurement is reproducible from the picture', () => {
  for (const row of STATE_PATTERNS) {
    const facelets = toFacelets(applyAlg(SOLVED, row.alg));
    assert.equal(symmetryOrder(facelets), row.order, `${row.alg}: symmetry order`);
    assert.equal(24 % row.order, 0, `${row.alg}: an order of ${row.order} does not divide 24`);
    assert.ok(row.order >= 2, `${row.alg}: order 1 is not a pattern and must not be in the ledger`);

    let wrong = 0, blank = 0;
    for (let k = 0; k < 6; k++) {
      const face = facelets.slice(k * 9, k * 9 + 9);
      for (const ch of face) if (ch !== FACE_ORDER[k]) wrong++;
      if (new Set(face).size === 1) blank++;
    }
    assert.equal(wrong, row.wrong, `${row.alg}: stickers reading wrong`);
    assert.equal(blank, row.blank, `${row.alg}: faces showing one colour`);
    assert.ok(wrong > 0, `${row.alg}: a solved cube is not a pattern`);
  }
});

test('no picture appears twice, and the solved cube does not appear at all', () => {
  const looks = new Set(STATE_PATTERNS.map((r) => r.look));
  assert.equal(looks.size, STATE_PATTERNS.length, 'two rows are the same picture held differently');
  assert.ok(!looks.has(canonicalLook(toFacelets(SOLVED))),
    'the solved cube is what patterns are measured from, not one of them');
});

test('the three independently proved minima appear at exactly those lengths', () => {
  // Proved by meet in the middle, which is exact to 10 moves and shares no search with this walk.
  // Lines is the interesting one: the book prints a 14-move algorithm for a 6-move picture.
  const PROVED = { 'The Checkerboard': 6, 'Plus/Minus': 6, Lines: 6 };
  for (const [name, minimum] of Object.entries(PROVED)) {
    const row = STATE_PATTERNS.find((r) => r.name === name);
    assert.ok(row, `${name} is missing from the ledger`);
    assert.equal(row.moves, minimum, `${name}: the ledger and the oracle disagree about the minimum`);
  }
});

test('the ledger spans more than one symmetry order, or the search found nothing', () => {
  // A ledger of 213 rows all at the same order would pass every assertion above while being the
  // output of a broken criterion. The measured distribution at depth 7 is 1 at order 24, 25 at 8 and
  // 187 at 4; this asserts the shape rather than the exact counts, which move with the radius.
  const orders = new Set(STATE_PATTERNS.map((r) => r.order));
  assert.ok(orders.size >= 3, `only ${orders.size} distinct symmetry orders in the ledger`);
  assert.ok(orders.has(24), 'no picture that looks the same from every angle — the Checkerboard is one');
  // Sizes pinned, because every assertion in this file is about rows that SURVIVED. An audit showed a
  // truncated ledger passing everything: delete a family and nothing noticed. These two numbers move
  // only when the search radius or the dedup rule moves, and both are deliberate acts.
  assert.equal(STATE_PATTERNS.length, 95,
    'the family count changed — regenerate at the same depth, or say why the number moved');
  // DISTINCT pictures, not array entries. Counting entries let a distinct rotation class disappear
  // behind a duplicated variant: set one row's `variants[0]` to its own `alg` and the array still
  // holds 213 strings while the ledger accounts for 212 pictures. Found by audit.
  const everyAlg = STATE_PATTERNS.flatMap((r) => [r.alg, ...r.variants]);
  assert.equal(everyAlg.length, 213, 'the ledger no longer lists 213 maneuvers');
  const distinctLooks = new Set(everyAlg.map((alg) => canonicalLook(toFacelets(applyAlg(SOLVED, alg)))));
  assert.equal(distinctLooks.size, 213,
    `the ledger's 213 maneuvers reach only ${distinctLooks.size} distinct pictures — a class has been lost behind a duplicate`);
  const maxWrong = Math.max(...STATE_PATTERNS.map((r) => r.wrong));
  assert.ok(maxWrong >= 24, `the busiest picture only has ${maxWrong} stickers wrong`);
});

test('the set patterns are sets: their sizes are derived and their predicates agree with them', () => {
  assert.ok(SET_PATTERNS.length > 0);
  for (const s of SET_PATTERNS) {
    assert.ok(Number.isFinite(s.size) && s.size > 1,
      `${s.id}: a set pattern with ${s.size} members is a state, not a set`);
    assert.ok(Array.isArray(s.parts) && s.parts.length > 0, `${s.id}: no projection parts`);
    // A cost of null is the honest answer for one nobody measured — "never invent data" — but a
    // number must come in a pair, because a saving with no baseline is not a saving.
    assert.equal(s.meanMoves === null, s.meanSolve === null,
      `${s.id}: one of the two costs is recorded and the other is not`);
    if (s.meanMoves !== null) {
      assert.ok(s.meanMoves < s.meanSolve,
        `${s.id}: reaching a SUPERSET of solved cannot cost more than solving`);
    }
  }
  // The solved cube satisfies every set pattern, since each is a relaxation of it. Checked through the
  // app's own piece model rather than through the generator's predicates.
  assert.ok(SOLVED.ep.every((v, i) => v === i) && SOLVED.cp.every((v, i) => v === i));
});

// ---- the solving phases, which are set patterns too ---------------------------------------------

test('every phase picture claims only what its phase guarantees', () => {
  // `solver-phases.mjs` measures each sticker's colour SET over 4,000 cubes built to satisfy the
  // phase, requires the answer to be unchanged at 2,000, and where two independent generators both
  // apply requires them to agree on all 54 — so a picture that over-claimed would throw on import.
  // These are the structural claims on top of that.
  assert.ok(SOLVER_PHASES.length >= 25, `only ${SOLVER_PHASES.length} phases`);
  const solvedFacelets = toFacelets(SOLVED);
  for (const p of SOLVER_PHASES) {
    assert.equal(p.picture.length, 54, `${p.id}: a picture is 54 stickers`);
    assert.equal(p.sets.length, 54, `${p.id}: a colour set per sticker`);
    assert.equal(p.settled + p.narrowed + p.free, 54, `${p.id}: the three counts must cover the cube`);
    for (let i = 0; i < 54; i++) {
      const set = p.sets[i];
      assert.ok(set.length >= 1 && set.length <= 6, `${p.id}: sticker ${i} can show ${set.length} colours`);
      // The picture is a rendering of the set and must not disagree with it.
      const want = set.length === 1 ? set : set.length <= 3 ? '?' : '-';
      assert.equal(p.picture[i], want, `${p.id}: sticker ${i} draws as ${p.picture[i]} for a set of ${set}`);
      if (p.relaxationOfSolved) {
        // The solved cube is a member of every phase that asks for less than solved, so its colour
        // must be IN every set — not merely equal to the settled ones. An audit showed a generator
        // that silently dropped members passing everything here, because a set that is too small
        // still looks settled. This is the cheapest check that catches an omission anywhere.
        assert.ok(set.includes(solvedFacelets[i]),
          `${p.id}: sticker ${i} allows ${set}, which excludes the ${solvedFacelets[i]} a solved cube shows there`);
      }
    }
    for (let f = 0; f < 6; f++) assert.equal(p.picture[f * 9 + 4], FACE_ORDER[f], `${p.id}: centre ${f}`);
  }
  // At least one phase must have been built two independent ways, or the cross-check is decoration.
  assert.ok(SOLVER_PHASES.some((p) => p.checkedBothWays), 'no phase was built two ways');
});

test('exactly one phase is not a partial solve, and it really is not one', () => {
  // Every phase here asks for LESS than a solved cube, so a solved cube satisfies it — except the
  // daisy, which gathers the bottom-colour edges round the TOP centre. It is the commonest way a
  // child is actually taught to start and the only phase in this file that a solved cube fails.
  // The flag is asserted in both directions so it cannot be set carelessly on a phase that does not
  // need it, which would switch off the check above for that phase in silence.
  const odd = SOLVER_PHASES.filter((p) => !p.relaxationOfSolved);
  assert.equal(odd.length, 1, `${odd.length} phases claim not to be partial solves: ${odd.map((p) => p.id).join(', ')}`);
  assert.equal(odd[0].id, 'daisy');
  const solvedFacelets = toFacelets(SOLVED);
  const disagreements = odd[0].sets.filter((set, i) => set.length === 1 && set !== solvedFacelets[i]).length;
  assert.ok(disagreements > 0, 'the daisy is flagged as not a partial solve but agrees with solved everywhere');
  for (const p of SOLVER_PHASES) {
    if (p.relaxationOfSolved) {
      const bad = p.sets.findIndex((set, i) => set.length === 1 && set !== solvedFacelets[i]);
      assert.equal(bad, -1, `${p.id} disagrees with a solved cube at sticker ${bad} but is not flagged`);
    }
  }
});

test('more than one method is represented, and every phase ends somewhere new', () => {
  const methods = new Set(SOLVER_PHASES.map((p) => p.method));
  assert.ok(methods.size >= 9, `only ${methods.size} methods: ${[...methods].join(', ')}`);
  // Every method must finish at a solved cube, or it is not a solving method.
  for (const m of methods) {
    const last = SOLVER_PHASES.filter((p) => p.method === m).at(-1);
    assert.equal(last.settled, 54, `${m} does not end solved; its last phase is ${last.name}`);
  }
});

test('the app\'s phases nest, and stage 5 settles nothing new to look at', () => {
  const byId = Object.fromEntries(SOLVER_PHASES.map((p) => [p.id, p]));
  const settledSet = (p) => new Set(p.sets.map((s, i) => (s.length === 1 ? i : -1)).filter((i) => i >= 0));
  const ORDER = ['cross', 'first-layer', 'two-layers', 'top-cross', 'top-face'];
  for (let i = 1; i < ORDER.length; i++) {
    const before = settledSet(byId[ORDER[i - 1]]);
    const after = settledSet(byId[ORDER[i]]);
    for (const j of before) {
      assert.ok(after.has(j), `${ORDER[i]} does not settle sticker ${j}, which ${ORDER[i - 1]} already did`);
    }
    assert.ok(after.size > before.size, `${ORDER[i]} settles nothing that ${ORDER[i - 1]} did not`);
  }

  // The product finding, asserted so it cannot quietly stop being true. The owner's stage 5 asks for
  // the top corners to be in their own places while free to be twisted, and a twist rotates a corner's
  // three stickers among themselves — so it SETTLES no sticker the top cross had not already settled.
  // Only the narrowed state distinguishes them, and without it a child could not see they had finished.
  assert.equal(byId['corners-home'].settled, byId['top-cross'].settled,
    'stage 5 now settles a different number of stickers than the top cross — the finding has moved');
  assert.ok(byId['corners-home'].narrowed > 0,
    'stage 5 must narrow its placed-but-turnable corners, or it draws as the top cross');
  assert.equal(byId['top-cross'].narrowed, 0, 'the top cross has nothing narrowed');
});

test('a phase whose content is a constraint narrows rather than settles', () => {
  const byId = Object.fromEntries(SOLVER_PHASES.map((p) => [p.id, p]));
  // ZZ's EOLine orients every edge and places two. Orienting settles nothing on its own, so the whole
  // phase comes to ten stickers: six centres and the two placed edges. That is the measured reason ZZ
  // is hard to learn, and it is the sharpest example of why "settled" alone was not enough.
  assert.equal(byId['zz-eoline'].settled, 10, 'EOLine settles the centres and its two line edges');
  assert.equal(byId['zz-eoline'].narrowed, 0, 'orienting edges alone narrows nothing either');
  // Thistlethwaite's G1 is edge orientation and nothing else, so it settles only the centres.
  assert.equal(byId.g1.settled, 6, 'G1 is invisible apart from the centres');
  // G3 is the half-turn group, where every facelet stays on its own axis — so every non-centre
  // sticker is narrowed to its own colour and the opposite one, and nothing is free. This is the same
  // fact the pattern search met from the other side when its two-colour criterion turned out to
  // enumerate a subgroup.
  assert.equal(byId.g3.free, 0, 'nothing in the half-turn group is free');
  assert.equal(byId.g3.narrowed, 48, 'every non-centre sticker is narrowed in the half-turn group');
  for (let i = 0; i < 54; i++) {
    if (i % 9 === 4) continue;
    assert.equal(byId.g3.sets[i].length, 2, `G3 sticker ${i} should be its colour or the opposite one`);
  }
});

test('no phase picture over-claims against members from a source that shares none of its code', () => {
  // The pictures are measured by shuffling pieces and repairing the cube's laws. These members come
  // from the METHOD SOLVER: run it on a scramble and stop at the first step after which the phase's
  // own predicate holds. Nothing is shared — not the generator, not the projections, not the
  // predicates, which are `methods/engine.js`'s and were written for solving rather than for drawing.
  //
  // The failure this catches is the one the convergence check cannot: a sampled colour set that is
  // too SMALL draws a phase as more finished than it is, and only a member from elsewhere can show it.
  const scrambles = seededScrambles(40, 0x1234, 25);
  let checked = 0;
  for (const [id, pred] of Object.entries(PREDICATE)) {
    const phase = SOLVER_PHASES.find((x) => x.id === id);
    if (!phase) continue;                       // six-cross and solved are patterns, not phases here
    let members = 0;
    for (const scr of scrambles) {
      let s = applyAlg(SOLVED, scr);
      for (const step of solveByMethod(s).steps) {
        s = applyAlg(s, step.alg);
        if (pred(s)) break;
      }
      if (!pred(s)) continue;
      members++;
      const f = toFacelets(s);
      for (let j = 0; j < 54; j++) {
        checked++;
        assert.ok(phase.sets[j].includes(f[j]),
          `${id} sticker ${j}: the picture allows ${phase.sets[j]} but a real cube at this phase shows ${f[j]}`);
      }
    }
    assert.ok(members >= scrambles.length / 2,
      `${id}: only ${members} members could be built, so this case is nearly vacuous`);
  }
  assert.ok(checked > 5000, `only ${checked} sticker comparisons — not enough to mean anything`);
});

/**
 * A phase's predicate, written here from its declarative fields — a SECOND implementation.
 *
 * `solver-phases.mjs` turns those fields into a generator; this turns them into a test. Neither reads
 * the other, so a generator that quietly drops members shows up as a member this predicate accepts
 * and the picture forbids.
 */
function phasePredicate(p) {
  const EDGE_NAMES = ['UR', 'UF', 'UL', 'UB', 'DR', 'DF', 'DL', 'DB', 'FR', 'FL', 'BL', 'BR'];
  const CORNER_NAMES = ['URF', 'UFL', 'ULB', 'UBR', 'DFR', 'DLF', 'DBL', 'DRB'];
  const eIdx = (n) => EDGE_NAMES.indexOf(n);
  const cIdx = (n) => CORNER_NAMES.indexOf(n);
  const solvedE = (p.solved ?? []).filter((n) => n.length === 2).map(eIdx);
  const solvedC = (p.solved ?? []).filter((n) => n.length === 3).map(cIdx);
  const placedC = (p.placed ?? []).map(cIdx);
  const orientE = p.orientEdges === 'all' ? EDGE_NAMES.map(eIdx) : (p.orientEdges ?? []).map(eIdx);
  const orientC = p.orientCorners === 'all' ? CORNER_NAMES.map(cIdx) : (p.orientCorners ?? []).map(cIdx);
  const sliceSlots = ['FR', 'FL', 'BL', 'BR'].map(eIdx);
  return (s) => {
    for (const i of solvedE) if (s.ep[i] !== i || s.eo[i] !== 0) return false;
    for (const i of solvedC) if (s.cp[i] !== i || s.co[i] !== 0) return false;
    for (const i of placedC) if (s.cp[i] !== i) return false;
    // An oriented EDGE is one whose cubie sits somewhere with flip zero, wherever that is.
    for (const cubie of orientE) { const at = s.ep.indexOf(cubie); if (s.eo[at] !== 0) return false; }
    for (const cubie of orientC) { const at = s.cp.indexOf(cubie); if (s.co[at] !== 0) return false; }
    if (p.slice) for (const slot of sliceSlots) if (!sliceSlots.includes(s.ep[slot])) return false;
    return true;
  };
}

test('no phase picture over-claims, on EVERY phase, not the five that had an easy source', () => {
  // The audit's sharpest remaining finding: the method-solver check above reaches only the five
  // phases `methods/engine.js` has predicates for. A generator that dropped members of Roux's first
  // block — the named break was rejecting any member showing F at sticker 0 — passed everything.
  //
  // This walks the MEMBER GRAPH: start from cubes known to be in the phase, apply a turn or two, keep
  // whatever still satisfies the independently written predicate. `R U2` preserves Roux's block and
  // shows F at sticker 0, which is exactly the member that break removed.
  const rnd = lcg(0x9e37);
  let totalChecked = 0;
  for (const phase of SOLVER_PHASES) {
    if (phase.relaxationOfSolved === false) continue;   // the daisy: SOLVED is not a member of it
    // A phase is described one of two ways and must be described one of them. A coset phase like
    // Thistlethwaite's G3 has NO piece constraints at all, and the first version of this case built a
    // predicate from its absent fields, got one that accepted every cube, and reported G3's picture as
    // over-claiming. The picture was right and the test was wrong.
    const hasPieces = Boolean(phase.solved || phase.placed || phase.orientEdges || phase.orientCorners || phase.slice);
    assert.ok(hasPieces || phase.generators,
      `${phase.id} is described neither by pieces nor by generators, so nothing here can check it`);
    const pred = hasPieces ? phasePredicate(phase) : () => true;
    const moves = hasPieces ? MOVE_NAMES : phase.generators;   // inside a subgroup, every walk stays in it
    if (hasPieces) assert.ok(pred(SOLVED), `${phase.id}: a solved cube must satisfy a phase that asks for less`);
    const pool = [SOLVED];
    let found = 0;
    for (let i = 0; i < 4000 && found < 120; i++) {
      let s = pool[Math.floor(rnd() * pool.length)];
      const steps = 1 + Math.floor(rnd() * 3);
      for (let k = 0; k < steps; k++) s = applyMove(s, moves[Math.floor(rnd() * moves.length)]);
      if (!pred(s)) continue;
      found++;
      if (pool.length < 400) pool.push(s);
      const f = toFacelets(s);
      for (let j = 0; j < 54; j++) {
        totalChecked++;
        assert.ok(phase.sets[j].includes(f[j]),
          `${phase.id} sticker ${j}: the picture allows ${phase.sets[j]} but a cube satisfying the phase shows ${f[j]}`);
      }
    }
    assert.ok(found >= 20, `${phase.id}: only ${found} members found by walking — this phase is barely checked`);
  }
  assert.ok(totalChecked > 50000, `only ${totalChecked} comparisons`);
});
